Repository garvitnegi17/planetoid, pull requests merged in 2025-01, with the labels that each got.

#11 START bitton fixed
  website/pages/games.html
Labels: enhancement, SWOC, BEGINNER

#15 fixed the improper scaling of games page
  website/pages/games.html
  website/styles/style.css
Labels: SWOC, INTERMEDIATE

#17 UI update
  bg.png
  cs1.png
  cs2.png
  images/flappySpaceShuttle.png
  images/tictactoe.png
  index.html
  pl.png
  r.svg
  ttt.png
  website/pages/games.html
  website/styles/style.css
Labels: SWOC, ADVANCE

#20 tic-toc-toe levels are ready issue #12 is ready
  .vscode/settings.json
  website/pages/tictactoe.html
  website/scripts/tic_tac_toe_script.js
  website/styles/tic_tac_toe_style.css
Labels: SWOC, ADVANCE

#22 UI/UX Update
  .vscode/settings.json
  website/styles/style.css
Labels: SWOC, INTERMEDIATE

#21 Fix Issue #6 Make Flappy space shuttle Mobile friendly
  website/pages/flappyBird.html
  website/scripts/flappyBird_script.js
  website/styles/flappyBird_style.css
Labels: SWOC, ADVANCE

#29 New update
  6.png
  7.png
  contributor.js
  countributor.html
  index.html
  visitor.css
  visitor.js
  website/pages/games.html
  website/pages/team.html
  website/styles/style.css
Labels: enhancement, SWOC, ADVANCE

#30 Button update
  countributor.html
  cvkj.png
  fav.png
  favicon.ico
  index.html
  rocket.svg
  st.svg
  website/pages/games.html
  website/styles/style.css
Labels: enhancement, SWOC, BEGINNER

#59 Enhance Scroll-to-Top with Circular Progress Indicator
  website/pages/countributor.html
  website/pages/games.html
  website/scripts/visitor.js
  website/styles/visitor.css
Labels: enhancement, SWOC, BEGINNER

#61 Breakout Game added>>
  images/breakout images/Breakhome.jpg
  images/breakout images/breakback.png
  index.html
  website/pages/break.html
  website/pages/games.html
  website/scripts/break.js
  website/styles/break.css
Labels: enhancement, SWOC, ADVANCE

#63 Add Snake Sphere Game
  images/Alien_catcher-images/Snake Sphere/snake.jpg
  index.html
  website/pages/Snake.html
  website/pages/games.html
  website/scripts/snake.js
Labels: enhancement, SWOC, ADVANCE

#82 fixed Popup Message of Overall Winner
  website/pages/tictactoe.html
  website/scripts/tic_tac_toe_script.js
Labels: enhancement, SWOC, INTERMEDIATE

#81 Fixed Memory Matching Game
  images/memory images/earth2.png
  images/memory images/memoryback2-ezgif.com-webp-to-jpg-converter.jpg
  images/memory images/rocket23.jpg
  images/memory images/rocket24.jpg
  images/memory images/rocket26.jpg
  images/memory images/rocket27.jpg
  images/memory images/rocket28.jpg
  images/memory images/rocket4.jpg
  images/memory images/rocket6.jpg
  index.html
  website/pages/games.html
  website/pages/memory.html
  website/scripts/memory.js
  website/styles/memory.css
Labels: enhancement, SWOC, ADVANCE
