Repository garvitnegi17/planetoid, pull requests merged in 2025-02, with the labels that each got.

#85 Enhance Contributor page
  website/pages/countributor.html
Labels: enhancement, SWOC, BEGINNER

#97 added contributors section
  README.md
Labels: enhancement, SWOC, INTERMEDIATE

#96 re-imagined play buttons
  website/pages/games.html
  website/styles/style.css
Labels: enhancement, IWOC2025, Medium

#108 Updated README.md
  README.md
  audio/Tile_Sequence_Audio/click.mp3
  audio/Tile_Sequence_Audio/error.mp3
  favicon/tile_favicon.ico
  images/Tile_Sequence_images/Tile_Sequence_dashboard.jpg
  images/Tile_Sequence_images/tile_background.jpg
  website/pages/games.html
  website/pages/tile.html
  website/scripts/tile.js
  website/styles/tile.css
Labels: enhancement, SWOC, BEGINNER
